### ISSUE TITLE
Hangs on separate instances of RelayStore

### ISSUE THREAD

**Issue by Naoto-Ida** [sibelius/react-native-relay-example#2]
Thanks for the great example. This is a question more than an issue.

I'm running into issues where the query never executes when having more than one instances of `RelayStore`.

Basically I have a RN app that relies on a npm library that contains common Components and Relay Containers for our company.

I need to pass the Relay env from the RN app to the library so that it can do queries and mutations with the same endpoint & headers.

I added your `RelayStore.js` to both projects and set the same env to both, but any use of `RelayStore.js` in the library fails.

**Comment by sibelius** [comment]
The relay prop of the component is the same as the RelayStore passed by createRenderer

`this.props.relay === RelayStore`

u should just keep the same RelayStore on Relay.Renderer (createRenderer) and you will be fine
