### ISSUE TITLE
Network Failed 

### ISSUE THREAD

**Issue by thayasgm** [sibelius/react-native-relay-example#3]
I have go through your code and tried on my react native App using default data, but i got  network request failed error. I dont know how to solve this. Kindly solve this

**Comment by sibelius** [comment]
you should modify the network layer here: https://github.com/sibelius/react-native-relay-example/blob/master/src/app.js#L13

to point to your server endpoint

I recommend starting using my boilerplate: https://github.com/entria/graphql-dataloader-boilerplate

**Comment by sibelius** [comment]
try to use adb reverse on android

reopen this if needed
